# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            edit_mode:
                format_on_edit: Yes
                format_on_cancel_edit: Yes
                format_on_revert: Yes
            label: Image
            fields:
                image_source:
                    plugin_setting:
                        name: image_source
                    label: 'Image source'
                    type: radios
                    value: _NO_IMAGE
                    values:
                        _NO_IMAGE:
                            label: "Don't show an image"
                        _CUSTOM_IMAGE:
                            label: Show an image
                        _STICKY_IMAGE:
                            label: Auto-show image from destination content item
                    format_onchange: Yes
                    note_below: |
                        If you choose auto-show, then an image marked as "sticky" on the destination content item will be used.
                image_thumbnail:
                    full_width: Yes
                    snippet:
                        html: ""            

                image:
                    plugin_setting:
                        name: image
                        foreign_key_to: file
                        use_value_for_plugin_name: "2"
                        
                    label: Image
                    pick_items:
                        path: zenario__content/hidden_nav/media/panel/hidden_nav/inline_images_for_reusable_plugins/panel
                        min_path: zenario__content/hidden_nav/media/panel/hidden_nav/inline_images_for_reusable_plugins/panel
                        max_path: zenario__content/hidden_nav/media/panel/hidden_nav/inline_images_for_reusable_plugins/panel
                        target_path: zenario__content/hidden_nav/media/panel/hidden_nav/inline_images_for_reusable_plugins/panel
                        select_phrase: Select image...
                    value: ""
                    format_onchange: Yes
                    validation:
                        required_if_not_hidden: Please select an image.
                canvas:
                    plugin_setting:
                        name: canvas
                    label: 'Image canvas'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: "1"
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: Yes
                width:
                    plugin_setting:
                        name: width
                    label: 'Width'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width in pixels.
                        numeric: The width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                height:
                    plugin_setting:
                        name: height
                    label: 'Height'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height in pixels.
                        numeric: The height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                offset:
                    plugin_setting:
                        name: offset
                    label: 'Offset'
                    type: text
                    style: 'width: 50px;'
                    value: "0"
                    slider:
                        min: "-10"
                        max: "10"
                        before_field: Yes
                        style: 'width: 200px;'
                    note_below: |
                        Moving the slider to the left will move the image left or down;
                        moving the slider to the right will move the image right or up.
                use_rollover:
                    plugin_setting:
                        name: use_rollover
                    label: 'Use a rollover image'
                    type: checkbox
                    value: ""
                    format_onchange: Yes
                rollover_image_thumbnail:
                    full_width: Yes
                    snippet:
                        html: ""            
                rollover_image:
                    plugin_setting:
                        name: rollover_image
                        foreign_key_to: file
                    label: 'Change image on rollover'
                    pick_items:
                        path: zenario__content/hidden_nav/media/panel/hidden_nav/inline_images_for_reusable_plugins/panel
                        min_path: zenario__content/hidden_nav/media/panel/hidden_nav/inline_images_for_reusable_plugins/panel
                        max_path: zenario__content/hidden_nav/media/panel/hidden_nav/inline_images_for_reusable_plugins/panel
                        target_path: zenario__content/hidden_nav/media/panel/hidden_nav/inline_images_for_reusable_plugins/panel
                        select_phrase: Select image...
                    value: ""
                alt_tag:
                    plugin_setting:
                        name: alt_tag
                        translate: Yes
                    multiple_edit:
                        original_value: ""
                    label: 'Overwrite image alt-tag'
                    type: text
                    maxlength: "255"
                    value: ""
                image_title:
                    plugin_setting:
                        name: image_title
                        translate: Yes
                    multiple_edit:
                        original_value: ""
                    label: 'Overwrite image title attribute'
                    type: text
                    value: ""
                floating_box_title:
                    plugin_setting:
                        name: floating_box_title
                        translate: Yes
                    multiple_edit:
                        original_value: ""
                    label: 'Overwrite image floating box title'
                    type: editor
                    cols: "70"
                    rows: "4"
                    value: ""
        text:
            label: 'Title & HTML'
            fields:
                title:
                    plugin_setting:
                        name: title
                        is_searchable_content: "1"
                        use_value_for_plugin_name: "1"
                        translate: Yes
                    label: 'Title'
                    type: text
                    width: "150"
                    maxlength: "255"
                    value: ""
                text:
                    plugin_setting:
                        name: text
                        is_searchable_content: "1"
                        translate: Yes
                    label: 'HTML'
                    type: editor
                    insert_link_button:
                        exists: Yes
                    cols: "80"
                    rows: "10"
                    value: ""
                use_phrases:
                    plugin_setting:
                        name: use_phrases
                    label: 'Use Visitor Phrases'
                    type: checkbox
                    value: ""
                    note_below: |
                        When enabled, Visitor Phrases will be merged into the above fields.
                                                    For example, use [[_MY_PHRASE]] to merge a Phrase called _MY_PHRASE.
        destination:
            label: Destination
            fields:
                link_type:
                    plugin_setting:
                        name: link_type
                    label: 'Destination'
                    type: radios
                    value: _NO_LINK
                    values:
                        _NO_LINK:
                            ord: "1"
                            label: No link
                        _CONTENT_ITEM:
                            ord: "2"
                            label: Link to a Content Item
                        _EXTERNAL_URL:
                            ord: "3"
                            label: Link to an external URL
                        _ENLARGE_IMAGE:
                            ord: "4"
                            label: Enlarge image in floating box
                    format_onchange: Yes
                hyperlink_target:
                    plugin_setting:
                        name: hyperlink_target
                        foreign_key_to: content
                        dangling_cross_references: delete_instance
                        use_value_for_plugin_name: "4"
                    label: 'Content Item'
                    pick_items:
                        by_language: Yes
                        min_path: zenario__content/nav/languages/panel
                        max_path: zenario__content/nav/content/panel
                        target_path: zenario__content/nav/content/panel
                        disallow_refiners_looping_on_min_path: Yes
                        select_phrase: Select Content Item...
                        hide_remove_button: Yes
                    validation:
                        required_if_not_hidden: Please select a content item
                    format_onchange: Yes
                use_translation:
                    plugin_setting:
                        name: use_translation
                    label: 'Use translation chain'
                    type: checkbox
                    value: ""
                    note_below: |
                        If the destination Content Item has a translation in the visitor's language, link to that.
                                                    (Recommended for Banners placed on the Layout or Template Family Layer.)
                hide_private_item:
                    plugin_setting:
                        name: hide_private_item
                    label: 'Privacy'
                    type: select
                    value: __ALWAYS_SHOW
                    values:
                        _ALWAYS_SHOW:
                            ord: "1"
                            label: Always show, even if the target item is private
                        _PRIVATE:
                            ord: "2"
                            label: Only show to visitors who can see the target Item
                        _LOGGED_OUT:
                            ord: "3"
                            label: Only show to visitors who are logged out
                        _LOGGED_IN:
                            ord: "4"
                            label: Always show to visitors who are logged in
                use_download_page:
                    plugin_setting:
                        name: use_download_page
                    label: 'Use a download page'
                    type: checkbox
                    value: ""
                    note_below: |
                        Link to the file's download page, rather than a direct link to the file.
                                                    Note that this option only applies to Document Content Items.
                    hidden: Yes
                url:
                    plugin_setting:
                        name: url
                    label: 'External URL'
                    type: url
                    maxlength: "255"
                    value: ""
                target_blank:
                    plugin_setting:
                        name: target_blank
                    label: 'Open in a new window'
                    type: checkbox
                    value: ""
                enlarge_canvas:
                    plugin_setting:
                        name: enlarge_canvas
                    label: 'Enlarged image canvas'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: "1"
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                    format_onchange: Yes
                enlarge_width:
                    plugin_setting:
                        name: enlarge_width
                    label: 'Width'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter an enlarged width.
                        numeric: The enlarged width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                enlarge_height:
                    plugin_setting:
                        name: enlarge_height
                    label: 'Height'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter an enlarged height.
                        numeric: The enlarged height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
    module_class_name: zenario_banner
