# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: external_programs
    title: Editing settings for external programs
    tabs:
        antiword:
            label: Antiword
            edit_mode:
                priv: _PRIV_EDIT_SITE_SETTING
                enabled: Yes
                on: No
                format_on_edit: Yes
                format_on_cancel_edit: Yes
                format_on_revert: Yes
            fields:
                desc:
                    full_width: Yes
                    snippet:
                        html: |
                            <p>
                                If you create a Document Content Item with a Word document, the CMS will attempt to
                                scan the Word document and create a plain-text extract.
                                This extract will not be visible, but will be used by the Search Results Module to search
                                the contents of the document and show it in the search results.
                            </p><p>
                                For Word documents with the new <code>.docx</code> extension,
                                the CMS can create an extract without help.
                            </p><p>
                                For Word documents with the old <code>.doc</code> extension,
                                the CMS needs the help of an external tool called Antiword.
                            </p><p>
                                If Antiword is not installed on your server then your server administrator will need to install it;
                                e.g. by running:
                                <br/>
                                <code>&nbsp; &nbsp; sudo apt-get install antiword</code>
                                <br/>
                                on Ubuntu.
                            </p><p>
                                The CMS can only use Antiword if it is running on a Unix-based server;
                                there is not support for this feature on a Windows server.
                            </p>
                antiword_path:
                    name: antiword_path
                    site_setting:
                        name: antiword_path
                    label: 'Antiword Path:'
                    type: varchar(255)
                    style: 'width: 300px; margin-right: 0.5em;'
                    value: antiword
                test:
                    same_row: Yes
                    type: submit
                    value: Test
                    class: submit
                    can_be_pressed_in_view_mode: Yes
                    format_onchange: Yes
                    note_below: |
                        You should enter the path to the <code>antiword</code> program in this field, e.g.: <code>/usr/bin/antiword</code>
                                                        <br/>
                                                        If this location is in your server's PATH environment variable, then you can just enter the name of the program.
            show_errors_after_field: desc
            notices:
                success:
                    show: ""
                    type: success
                    message: Antiword is working successfully.
                error:
                    show: ""
                    type: error
                    message: Antiword is not correctly set up.
        pdftotext:
            label: PDF-to-Text
            edit_mode:
                priv: _PRIV_EDIT_SITE_SETTING
                enabled: Yes
                on: No
                format_on_edit: Yes
                format_on_cancel_edit: Yes
            fields:
                desc:
                    full_width: Yes
                    snippet:
                        html: |
                            <p>
                                If you create a Document Content Item with a PDF file, the CMS will attempt to
                                scan the PDF file and create a plain-text extract.
                                This extract will not be visible, but will be used by the Search Results Module to search
                                the contents of the file and show it in the search results.
                            </p><p>
                                To get an extract from a PDF file,
                                the CMS needs the help of a program called pdftotext,
                                which is part of an external library called Poppler.
                            </p><p>
                                If Poppler is not installed on your server then your server administrator will need to install it;
                                e.g. by running:
                                <br/>
                                <code>&nbsp; &nbsp; sudo apt-get install poppler-utils</code>
                                <br/>
                                on Ubuntu.
                            </p><p>
                                The CMS can only use pdftotext and Poppler if it is running on a Unix-based server;
                                there is not support for this feature on a Windows server.
                            </p>
                pdftotext_path:
                    name: pdftotext_path
                    site_setting:
                        name: pdftotext_path
                    label: 'pdftotext Path:'
                    value: pdftotext
                    type: varchar(255)
                    style: 'width: 300px; margin-right: 0.5em;'
                test:
                    same_row: Yes
                    type: submit
                    value: Test
                    class: submit
                    can_be_pressed_in_view_mode: Yes
                    format_onchange: Yes
                    note_below: |
                        You should enter the path to the <code>pdftotext</code> program in this field, e.g.: <code>/usr/bin/pdftotext</code>
                                                        <br/>
                                                        If this location is in your server's PATH environment variable, then you can just enter the name of the program.
            show_errors_after_field: desc
            notices:
                success:
                    show: ""
                    type: success
                    message: pdftotext is working successfully.
                error:
                    show: ""
                    type: error
                    message: pdftotext is not correctly set up.

        ghostscript:
            label: Ghostscript
            edit_mode:
                priv: _PRIV_EDIT_SITE_SETTING
                enabled: Yes
                on: No
                format_on_edit: Yes
                format_on_cancel_edit: Yes
            fields:
                desc:
                    full_width: Yes
                    snippet:
                        html: |
                            <p>
                                If you create a Document Content Item with a PDF file, the CMS will attempt to
                                scan the PDF file and create a thumbnail of the first page that can be used as stick image.
                            </p><p>
                                To get a thumbnail from a PDF file,
                                the CMS needs the help of a program called "gs" (ghostscript).
                            </p><p>
                                If ghostscript is not installed on your server then your server administrator will need to install it;
                                e.g. by running:
                                <br/>
                                <code>&nbsp; &nbsp; sudo apt-get install ghostscript</code>
                                <br/>
                                on Ubuntu.
                            </p><p>
                                The CMS can only use ghostscript if it is running on a Unix-based server;
                                there is not support for this feature on a Windows server.
                            </p>
                ghostscript_dpi:
                    name: ghostscript_dpi
                    site_setting:
                        name: ghostscript_dpi
                    label: 'ghostscript output DPI:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a DPI number.
                        numeric: The DPI must be a number.
                    value: "72"
                    style: 'width: 6em; margin-right: 0.5em;'
                    note_below: |
                        This setting define the image definition that will be produced (higher definition also creates big images).
                        Recomended values can be any of 72, 150, 300, 600 (default 72).
                ghostscript_path:
                    name: ghostscript_path
                    site_setting:
                        name: ghostscript_path
                    label: 'ghostscript Path:'
                    value: gs
                    type: varchar(255)
                    style: 'width: 300px; margin-right: 0.5em;'
                test:
                    same_row: Yes
                    type: submit
                    value: Test
                    class: submit
                    can_be_pressed_in_view_mode: Yes
                    format_onchange: Yes
                    note_below: |
                        You should enter the path to the <code>gs</code> program in this field, e.g.: <code>/usr/bin/gs</code>
                        <br/>
                        If this location is in your server's PATH environment variable, then you can just enter the name of the program.
            show_errors_after_field: desc
            notices:
                success:
                    show: ""
                    type: success
                    message: ghostscript is working successfully.
                error:
                    show: ""
                    type: error
                    message: ghostscript is not correctly set up.
